name: Woodcutter
version: '${version}'
main: me.fortibrine.woodcutter.Woodcutter
api-version: 1.13

commands:
  level:
    description: "Команда для повышения уровня топора"
  sell:
    description: "Продать вещи"
  booster:
    description: "Установить бустер"
    usage: "/booster [Никнейм] [Бустер] [Время в секундах]"
  boosters:
    description: "Список бустеров"
    usage: "/boosters [add] [Никнейм] [Бустер] [Время в секундах] [Глобальный? (true/false)]"

permissions:
  woodcutter.*:
    default: op
    description: "All permissions"
    children:
      woodcutter.level: true
      woodcutter.sell: true
      woodcutter.booster: true
      woodcutter.boosters: true
      woodcutter.boosters.add: true
  woodcutter.level:
    default: true
    description: "Команда для повышения уровня топора"
  woodcutter.sell:
    default: true
    description: "Продать вещи"
  woodcutter.booster:
    default: op
    description: "Установить бустер игроку"
  woodcutter.boosters:
    default: true
    description: "Посмотреть список бустеров"
  woodcutter.boosters.add:
    default: op
    description: "Добавить бустер"