name: Woodcutter
version: '${project.version}'
main: me.fortibrine.woodcutter.Woodcutter
api-version: 1.13

commands:
  level:
    description: "Команда для повышения уровня топора"
  sell:
    description: "Продать вещи"

permissions:
  woodcutter.*:
    default: op
    description: "All permissions"
    children:
      woodcutter.level: true
      woodcutter.sell: true
  woodcutter.level:
    default: true
    description: "Команда для повышения уровня топора"
  woodcutter.sell:
    default: true
    description: "Продать вещи"